name: MineClickFt
authors: [ZINGDING, HS-Team, ChoungYoo]
version: v0.0.1-Release
main: ZINGDING.MineClickFt.mineclickft
api: [1.0.0]
website: "https://github.com/Dotory-Development/MineClickFt-Nukkit.git"